### ISSUE TITLE
Setting certs dir leads to inconsistent results

### ISSUE THREAD

**Issue by LeSpocky** [24367dfa/ansible-role-dehydrated#18]
## Motivation

Migrate from manually configured dehydrated from the official Debian package and default Debian configs to this role, ensuring a smooth transition with stable directories and meaningful diffs between old and new config (with `ansible-playbook --diff --check …`).

## Faulty Role Behaviour

Set these (which matches the defaults used by Debian):

```yaml
dehydrated_certs_dir: "/var/lib/dehydrated/certs"                # where the webserver expects the certs
dehydrated_config_dir: "/etc/dehydrated"                         # expecting configuration only here
dehydrated_contact_email: "post@example.com"
dehydrated_location: "/usr/local/lib/dehydrated"                 # where I want the Git checkout to be
dehydrated_wellknown_dir: "/var/lib/dehydrated/acme-challenges"  # where the webserver expects the challenges
```

First strange thing noticable on first run of `dehydrated`, accidentally _without_ sudo:

```
alex@falbala ~ % dehydrated --cron
# INFO: Using main config file /etc/dehydrated/config
mkdir: das Verzeichnis „/etc/dehydrated/accounts/aHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2RpcmVjdG9yeQo“ kann nicht angelegt werden: Keine Berechtigung
```

Although not intended he tries to create stuff in the config dir, which was not intended.  Then when running _with_ sudo:

```
alex@falbala ~ % sudo dehydrated --cron
[sudo] Passwort für alex: 
# INFO: Using main config file /etc/dehydrated/config
 + Creating chain cache directory /etc/dehydrated/chains
Processing git.home.lespocky.de
 + Creating new directory /etc/dehydrated/certs/git.home.lespocky.de ...
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 1 authorizations URLs from the CA
 + Handling authorization for git.home.lespocky.de
 + 1 pending challenge(s)
 + Deploying challenge tokens...
 + Responding to challenge for git.home.lespocky.de authorization...
 + Challenge is valid!
 + Cleaning challenge tokens...
 + Requesting certificate...
 + Checking certificate...
 + Done!
 + Creating fullchain.pem...
 + Done!
```

After that */var/lib/dehydrated/certs* is essentially empty except for _config_ and _hook.sh_ but more things were created below */etc/dehydrated*.  Especially the certs do not end up in my configured `dehydrated_certs_dir` as expected.

## Possible Direction Forward

I suspect `CERTDIR` should be set in config.  This might require an even more sophisticated approach involving `BASEDIR`.  The part from dehydrated docs/example reads like this:

```sh
# Base directory for account key, generated certificates and list of domains (default: $SCRIPTDIR -- uses config directory if undefined)
#BASEDIR=$SCRIPTDIR                                                        
                                                                           
# File containing the list of domains to request certificates for (default: $BASEDIR/domains.txt)
#DOMAINS_TXT="${BASEDIR}/domains.txt"                                      
                                                                           
# Output directory for generated certificates                              
#CERTDIR="${BASEDIR}/certs"                                                
                                                                           
# Output directory for alpn verification certificates                      
#ALPNCERTDIR="${BASEDIR}/alpn-certs"                                       
                                                                           
# Directory for account keys and registration information                  
#ACCOUNTDIR="${BASEDIR}/accounts"                                          
                                                                           
# Output directory for challenge-tokens to be served by webserver or deployed in HOOK (default: /var/www/dehydrated)
#WELLKNOWN="/var/www/dehydrated"                                           
```

See the Debian default config here[^1]:

```sh
CONFIG_D=/etc/dehydrated/conf.d
BASEDIR=/var/lib/dehydrated
WELLKNOWN="${BASEDIR}/acme-challenges"
DOMAINS_TXT="/etc/dehydrated/domains.txt"
```

Not sure if it can be done backwards compatible to what this role currently does?

[^1]: https://salsa.debian.org/letsencrypt-team/dehydrated/-/blob/debian/master/debian/config.sh
