### ISSUE TITLE
Feature: Default hook

### ISSUE THREAD

**Issue by penguineer** [24367dfa/ansible-role-dehydrated#7]
The Netz39 playbook currently looks like this:
```yaml
    - name: Setup Dehydrated
      include_role:
        name: ansible-role-dehydrated
      vars:
        dehydrated_contact_email: "{{ server_admin }}"
        dehydrated_domains:
          - name: "domain1"
            deploy_challenge_hook: "/bin/systemctl restart apache2"
          - name: "domain2"
            deploy_challenge_hook: "/bin/systemctl restart apache2"
          - name: "domain3"
            deploy_challenge_hook: "/bin/systemctl restart apache2"
```

The hook is identical for each domain, but has to be repeated everytime. 

As a user of the role I would like to be able to define a default hook that is used when no hook is defined for the domain.

(If a default hook exists and there is a single domain without a hook, that can be achieved by setting the hook to `/bin/true`, so no further default-hook disable is necessary.)

**Comment by LeSpocky** [comment]
What about a an additional variable with a structure like this:

```yaml
dehydrated_default_hooks:
  deploy_challenge_hook:
  clean_challenge_hook:
  sync_cert_hook:
  deploy_cert_hook:
  deploy_ocsp_hook:
  unchanged_cert_hook:
  invalid_challenge_hook:
  request_failure_hook:
  startup_hook:
```

And in your playbook:

```yaml
---
- name: My playbook
  hosts: all

  roles:
    - role: 24367dfa.dehydrated
      vars: 
        dehydrated_contact_email: acme@example.com
        dehydrated_default_hooks:
          deploy_cert_hook: /usr/bin/systemctl reload nginx
        dehydrated_domains:
          - name: foo.example.com
          - name: bar.example.com
            deploy_cert_hook: /usr/bin/true
          - name: baz.example.com
```

Not sure how to implement this however, but should not be too hard with jinja2?!
